// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats WHERE chat_id = ?
`

func (q *Queries) DeleteChat(ctx context.Context, chatID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChat, chatID)
	return err
}

const getChat = `-- name: GetChat :one
SELECT chat_id, greeted_at, created_at FROM chats WHERE chat_id = ?
`

func (q *Queries) GetChat(ctx context.Context, chatID int64) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, chatID)
	var i Chat
	err := row.Scan(&i.ChatID, &i.GreetedAt, &i.CreatedAt)
	return i, err
}

const getChatGreetedAt = `-- name: GetChatGreetedAt :one
SELECT greeted_at FROM chats WHERE chat_id = ?
`

func (q *Queries) GetChatGreetedAt(ctx context.Context, chatID int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getChatGreetedAt, chatID)
	var greeted_at sql.NullString
	err := row.Scan(&greeted_at)
	return greeted_at, err
}

const insertChat = `-- name: InsertChat :exec
INSERT OR IGNORE INTO chats (chat_id, created_at) VALUES (?, ?)
`

type InsertChatParams struct {
	ChatID    int64
	CreatedAt string
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) error {
	_, err := q.db.ExecContext(ctx, insertChat, arg.ChatID, arg.CreatedAt)
	return err
}

const listChatIDs = `-- name: ListChatIDs :many
SELECT chat_id FROM chats ORDER BY chat_id
`

func (q *Queries) ListChatIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listChatIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var chat_id int64
		if err := rows.Scan(&chat_id); err != nil {
			return nil, err
		}
		items = append(items, chat_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChatGreeted = `-- name: MarkChatGreeted :exec
UPDATE chats SET greeted_at = ? WHERE chat_id = ?
`

type MarkChatGreetedParams struct {
	GreetedAt sql.NullString
	ChatID    int64
}

func (q *Queries) MarkChatGreeted(ctx context.Context, arg MarkChatGreetedParams) error {
	_, err := q.db.ExecContext(ctx, markChatGreeted, arg.GreetedAt, arg.ChatID)
	return err
}
