// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_usage.sql

package sqlcgen

import (
	"context"
)

const deleteDailyUsageBefore = `-- name: DeleteDailyUsageBefore :exec
DELETE FROM daily_usage WHERE day < ?
`

func (q *Queries) DeleteDailyUsageBefore(ctx context.Context, day string) error {
	_, err := q.db.ExecContext(ctx, deleteDailyUsageBefore, day)
	return err
}

const listDailyUsage = `-- name: ListDailyUsage :many
SELECT service_id, day, in_bytes, out_bytes, fetched_at
FROM daily_usage
WHERE service_id = ?1
  AND day >= ?2
  AND day <= ?3
ORDER BY day DESC
`

type ListDailyUsageParams struct {
	ServiceID int64
	From      string
	To        string
}

func (q *Queries) ListDailyUsage(ctx context.Context, arg ListDailyUsageParams) ([]DailyUsage, error) {
	rows, err := q.db.QueryContext(ctx, listDailyUsage, arg.ServiceID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyUsage
	for rows.Next() {
		var i DailyUsage
		if err := rows.Scan(
			&i.ServiceID,
			&i.Day,
			&i.InBytes,
			&i.OutBytes,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyUsage = `-- name: UpsertDailyUsage :exec
INSERT INTO daily_usage (service_id, day, in_bytes, out_bytes, fetched_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (service_id, day) DO UPDATE SET
  in_bytes   = excluded.in_bytes,
  out_bytes  = excluded.out_bytes,
  fetched_at = excluded.fetched_at
`

type UpsertDailyUsageParams struct {
	ServiceID int64
	Day       string
	InBytes   int64
	OutBytes  int64
	FetchedAt string
}

func (q *Queries) UpsertDailyUsage(ctx context.Context, arg UpsertDailyUsageParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyUsage,
		arg.ServiceID,
		arg.Day,
		arg.InBytes,
		arg.OutBytes,
		arg.FetchedAt,
	)
	return err
}
