// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_runs.sql

package sqlcgen

import (
	"context"
)

const deleteJobRunsBefore = `-- name: DeleteJobRunsBefore :exec
DELETE FROM daily_job_runs WHERE day < ?
`

func (q *Queries) DeleteJobRunsBefore(ctx context.Context, day string) error {
	_, err := q.db.ExecContext(ctx, deleteJobRunsBefore, day)
	return err
}

const getJobRun = `-- name: GetJobRun :one
SELECT ran_at FROM daily_job_runs WHERE day = ? AND job = ?
`

type GetJobRunParams struct {
	Day string
	Job string
}

func (q *Queries) GetJobRun(ctx context.Context, arg GetJobRunParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getJobRun, arg.Day, arg.Job)
	var ran_at string
	err := row.Scan(&ran_at)
	return ran_at, err
}

const insertJobRun = `-- name: InsertJobRun :exec
INSERT OR IGNORE INTO daily_job_runs (day, job, ran_at) VALUES (?, ?, ?)
`

type InsertJobRunParams struct {
	Day   string
	Job   string
	RanAt string
}

func (q *Queries) InsertJobRun(ctx context.Context, arg InsertJobRunParams) error {
	_, err := q.db.ExecContext(ctx, insertJobRun, arg.Day, arg.Job, arg.RanAt)
	return err
}
