// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Chat struct {
	ChatID    int64
	GreetedAt sql.NullString
	CreatedAt string
}

type DailyJobRun struct {
	Day   string
	Job   string
	RanAt string
}

type DailyUsage struct {
	ServiceID int64
	Day       string
	InBytes   int64
	OutBytes  int64
	FetchedAt string
}

type Setting struct {
	ID                  int64
	ReportEnabled       int64
	ReportTime          string
	TrafficAlertEnabled int64
	TrafficThresholds   string
	ExpiryAlertEnabled  int64
	ExpiryDays          int64
	UpdatedAt           string
}

type TrafficAlertState struct {
	ServiceID int64
	Threshold int64
	AlertedAt sql.NullString
}
