// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT report_enabled, report_time, traffic_alert_enabled, traffic_thresholds,
       expiry_alert_enabled, expiry_days, updated_at
FROM settings
WHERE id = 1
`

type GetSettingsRow struct {
	ReportEnabled       int64
	ReportTime          string
	TrafficAlertEnabled int64
	TrafficThresholds   string
	ExpiryAlertEnabled  int64
	ExpiryDays          int64
	UpdatedAt           string
}

func (q *Queries) GetSettings(ctx context.Context) (GetSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i GetSettingsRow
	err := row.Scan(
		&i.ReportEnabled,
		&i.ReportTime,
		&i.TrafficAlertEnabled,
		&i.TrafficThresholds,
		&i.ExpiryAlertEnabled,
		&i.ExpiryDays,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDefaultSettings = `-- name: InsertDefaultSettings :exec
INSERT OR IGNORE INTO settings (id, updated_at) VALUES (1, ?)
`

func (q *Queries) InsertDefaultSettings(ctx context.Context, updatedAt string) error {
	_, err := q.db.ExecContext(ctx, insertDefaultSettings, updatedAt)
	return err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings SET
  report_enabled        = ?,
  report_time           = ?,
  traffic_alert_enabled = ?,
  traffic_thresholds    = ?,
  expiry_alert_enabled  = ?,
  expiry_days           = ?,
  updated_at            = ?
WHERE id = 1
`

type UpdateSettingsParams struct {
	ReportEnabled       int64
	ReportTime          string
	TrafficAlertEnabled int64
	TrafficThresholds   string
	ExpiryAlertEnabled  int64
	ExpiryDays          int64
	UpdatedAt           string
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings,
		arg.ReportEnabled,
		arg.ReportTime,
		arg.TrafficAlertEnabled,
		arg.TrafficThresholds,
		arg.ExpiryAlertEnabled,
		arg.ExpiryDays,
		arg.UpdatedAt,
	)
	return err
}
