// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traffic_alert.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getTrafficAlertState = `-- name: GetTrafficAlertState :one
SELECT alerted_at FROM traffic_alert_state WHERE service_id = ? AND threshold = ?
`

type GetTrafficAlertStateParams struct {
	ServiceID int64
	Threshold int64
}

func (q *Queries) GetTrafficAlertState(ctx context.Context, arg GetTrafficAlertStateParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTrafficAlertState, arg.ServiceID, arg.Threshold)
	var alerted_at sql.NullString
	err := row.Scan(&alerted_at)
	return alerted_at, err
}

const upsertTrafficAlertState = `-- name: UpsertTrafficAlertState :exec
INSERT INTO traffic_alert_state (service_id, threshold, alerted_at)
VALUES (?, ?, ?)
ON CONFLICT (service_id, threshold) DO UPDATE SET alerted_at = excluded.alerted_at
`

type UpsertTrafficAlertStateParams struct {
	ServiceID int64
	Threshold int64
	AlertedAt sql.NullString
}

func (q *Queries) UpsertTrafficAlertState(ctx context.Context, arg UpsertTrafficAlertStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrafficAlertState, arg.ServiceID, arg.Threshold, arg.AlertedAt)
	return err
}
